services:
  api-gateway:
    env_file:
      - .dev.env
  auth-service:
    env_file:
      - .dev.env
  core-service:
    env_file:
      - .dev.env
  notification-service:
    env_file:
      - .dev.env
