services:
  api-gateway:
    image: api-gateway:latest
    ports:
      - "9000:8080"
    depends_on:
      - auth-service
      - core-service
      - notification-service
    env_file:
      - .env

  auth-service:
    image: auth-service:latest
    expose:
      - "8080"
    env_file:
      - .env

  core-service:
    image: core-service:latest
    expose:
      - "8080"
    depends_on:
      - auth-service
    env_file:
      - .env

  notification-service:
    image: notification-service:latest
    expose:
      - "8080"
    depends_on:
      - auth-service
    env_file:
      - .env


